version: '3.5'

services:
  docker-utils:
    image: docker-utils-ext:0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/root/.docker/config.json
      - ~/.docker-utils/templates:/templates
#    environment:
#      - ENGINE=docker
#      - SOCKET_HOST=hermes
#      - SOCKET_PORT=8080
#      - TEMPLATES_PATH=/templates/
    ports:
      - 8040:8080

  hermes:
    image: hermes:0.0.1
    ports:
      - 8041:8080

